/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 4 "uniform_test_send.c"
void __globinit_uniform_test_send(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 212 "/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h"
typedef unsigned long size_t;
#line 36 "../bin/../include/server.h"
typedef long long value_t;
#line 47 "../bin/../include/server.h"
struct INPUT {
   int num ;
   value_t inputs[256] ;
};
#line 179 "../bin/../include/crest.h"
extern void __CrestStoreZ(int  , unsigned long  )  __attribute__((__crest_skip__)) ;
#line 203
extern void __CrestInt(int *x )  __attribute__((__crest_skip__)) ;
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 466 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
#line 65 "../bin/../include/server.h"
extern void store_input(struct INPUT * ) ;
#line 4 "uniform_test_send.c"
int main(void) 
{ 
  int a ;
  int b ;
  int z ;
  struct INPUT *in ;
  void *tmp ;
  int __retres6 ;

  {
  __globinit_uniform_test_send();
  __CrestCall(2515, 76);
#line 6
  __CrestInt(& a);
#line 7
  __CrestInt(& b);
#line 8
  __CrestInt(& z);
  __CrestLoad(2516, (unsigned long )0, (long long )sizeof(*in));
#line 10
  tmp = malloc(sizeof(*in));
  __CrestClearStack(2517);
#line 10
  in = (struct INPUT *)tmp;
  __CrestLoad(2518, (unsigned long )0, (long long )3);
  __CrestStore(2519, (unsigned long )(& in->num));
#line 11
  in->num = 3;
  __CrestLoad(2520, (unsigned long )(& a), (long long )a);
  __CrestStore(2521, (unsigned long )(& in->inputs[0]));
#line 12
  in->inputs[0] = (value_t )a;
  __CrestLoad(2522, (unsigned long )(& b), (long long )b);
  __CrestStore(2523, (unsigned long )(& in->inputs[1]));
#line 13
  in->inputs[1] = (value_t )b;
  __CrestLoad(2524, (unsigned long )(& z), (long long )z);
  __CrestStore(2525, (unsigned long )(& in->inputs[2]));
#line 14
  in->inputs[2] = (value_t )z;
#line 15
  store_input(in);
  __CrestClearStack(2526);
#line 16
  printf((char const   * __restrict  )"Storing server input\n");
  __CrestClearStack(2527);
  __CrestLoad(2530, (unsigned long )(& a), (long long )a);
  __CrestLoad(2529, (unsigned long )0, (long long )50);
  __CrestApply2(2528, 14, (long long )(a > 50));
#line 18
  if (a > 50) {
    __CrestBranch(2531, 603, 1);
    {
    __CrestLoad(2535, (unsigned long )(& b), (long long )b);
    __CrestLoad(2534, (unsigned long )0, (long long )25);
    __CrestApply2(2533, 14, (long long )(b > 25));
#line 19
    if (b > 25) {
      __CrestBranch(2536, 604, 1);
      __CrestLoad(2540, (unsigned long )(& a), (long long )a);
      __CrestLoad(2539, (unsigned long )(& b), (long long )b);
      __CrestApply2(2538, 0, (long long )(a + b));
      __CrestStore(2541, (unsigned long )(& z));
#line 20
      z = a + b;
#line 21
      __CrestStoreZ(1, (unsigned long )(& z));
    } else {
      __CrestBranch(2537, 605, 0);
      __CrestLoad(2544, (unsigned long )(& a), (long long )a);
      __CrestLoad(2543, (unsigned long )0, (long long )20);
      __CrestApply2(2542, 0, (long long )(a + 20));
      __CrestStore(2545, (unsigned long )(& z));
#line 24
      z = a + 20;
#line 25
      __CrestStoreZ(1, (unsigned long )(& z));
    }
    }
  } else {
    __CrestBranch(2532, 606, 0);
    __CrestLoad(2548, (unsigned long )(& b), (long long )b);
    __CrestLoad(2547, (unsigned long )0, (long long )20);
    __CrestApply2(2546, 0, (long long )(b + 20));
    __CrestStore(2549, (unsigned long )(& z));
#line 28
    z = b + 20;
#line 29
    __CrestStoreZ(1, (unsigned long )(& z));
  }
  __CrestLoad(2550, (unsigned long )0, (long long )0);
  __CrestStore(2551, (unsigned long )(& __retres6));
#line 31
  __retres6 = 0;
  __CrestLoad(2552, (unsigned long )(& __retres6), (long long )__retres6);
  __CrestReturn(2553);
#line 4
  return (__retres6);
}
}
void __globinit_uniform_test_send(void) 
{ 


  {
  __CrestInit();
}
}
